### PR TITLE
Added label to bus

### PR DESCRIPTION
**Pull request by edo2313**

### CODE REVIEW

**Review by edo2313 — COMMENTED** [review]
It's not in the documentation but it's there, confirmed on VB-audio discord

**Comment by ChewbaccaCookie** [comment]
Okay, please try to merge latest main, in order to fix workflow

**Comment by ChewbaccaCookie** [comment]
Please try again :)

**Review by ChewbaccaCookie — APPROVED** [review]

**Comment by ChewbaccaCookie** [comment]
Please change version in package.json to "1.2.0" before merging :)

**Comment by ChewbaccaCookie** [comment]
Thank you for your Pull Request 👍🏼

**Pull request merged**
