### PR TITLE
feat: Add a way to set options for voicemeeter

### PR DESCRIPTION
**Pull request by jasperdevries**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Being able to set options within voicemeter through this package, not just bus or strip values but everything.

* **What is the current behavior?** (You can also link to an open issue here)
Currently this is not possible, i saw someone else also made a request for it [here](https://github.com/ChewbaccaCookie/voicemeeter-connector/issues/19)

* **What is the new behavior (if this is a feature change)?**
You can now set any command in voicemeter

* **Other information**:

### CODE REVIEW

**Comment by Ellarddekoeijer** [comment]
@ChewbaccaCookie Any chance that this can be merged? I need this exact functionality

**Comment by ChewbaccaCookie** [comment]
Hi @Ellarddekoeijer and @jasperdevries,
sry I got no notification for this. 
Thank you for your work.
The PR looks good. 
Could you please increase the package.json version by a minor release from v1.0.3 to v1.1.0? 
Then I would merge your changes.

**Comment by ChewbaccaCookie** [comment]
It seems that building is broken again. I'll have a look at this later on this day.

**Comment by jasperdevries** [comment]
Hello @ChewbaccaCookie , Thanks for looking at this. I updated the version in the package.json.

**Comment by ChewbaccaCookie** [comment]
Building Issues has been fixed in #32.

**Comment by jasperdevries** [comment]
@ChewbaccaCookie thanks for fixing these issues. I've manually merged the changes.

**Review by ChewbaccaCookie — APPROVED** [review]

**Comment by ChewbaccaCookie** [comment]
Thank you @jasperdevries for your contribution 🎉.

**Pull request merged**
