### PR TITLE
fix: Fixed labels and device name

### PR DESCRIPTION
**Pull request by edo2313**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug Fix

* **What is the current behavior?** (You can also link to an open issue here)
Getting label returns 0

* **What is the new behavior (if this is a feature change)?**
Getting label returns the correct value

* **Other information**:
Thanks to @terenc3 for pointing out the issue and suggesting a fix

### CODE REVIEW

**Comment by terenc3** [comment]
Works fine for me

grafik

The truncated text at the third entry also appears in voicemeeters dropdowns when using MME (in and out). I guess it is a problem there

**Comment by ChewbaccaCookie** [comment]
Hi, 
thank you @edo2313 and @terenc3. Your changes have been merged in PR #28.

**Comment by edo2313** [comment]
> 
> 
> Works fine for me (Label / device.name)
> 
> grafik
> 
> The truncated text at the third entry also appears in voicemeeters dropdowns when using MME (in and out). I guess it is a problem there

will check later, I only tested with the active one and not all devices so I coud have missed something in MME, but it should be the same as the others...
Also @ChewbaccaCookie remember to change the version number in package.json

**Comment by terenc3** [comment]
Nothing to check here. According to https://en.wikipedia.org/wiki/Windows_legacy_audio_components 
> Device name length in MME is restricted to 31 characters so long device names may appear only partially. 

grafik

**Pull request closed without merging**
